### ISSUE TITLE
Does thinky support update in place?

### ISSUE THREAD

**Issue by ipeisong** [neumino/thinky#153]
Can I update doc without loading it? If so, the listener 'save' will be triggered or not? Thanks.

**Comment by Tlvenn** [comment]
Unless I missed it, I believe in place update is missing from the doc.

**Comment by neumino** [comment]
I wrote about here:
http://thinky.io/documentation/api/query/#reql

But I guess it's kind of hard to find (there's not really a direct link to it). I've been thinking recently to write more about all these functions since while the docs work fine for people used to ReQL, they are probably a bit hard to read for people who never used it.

I'll try to find some time to do that.
