### ISSUE TITLE
.getJoin().changes().execute() fails, Expected type SELECTION but found SEQUENCE

### ISSUE THREAD

**Issue by davidje** [neumino/thinky#165]
Code: https://gist.github.com/davidje/92dc3051cdf4b38ca232

Output: 

Possibly unhandled ReqlRuntimeError: Expected type SELECTION but found SEQUENCE:
VALUE SEQUENCE in:
r.table("Users").merge(function(var_2) {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return r.branch(var_2.hasFields("id"), r.object("Accounts", r.table("Accounts").getAll(var_2("id"), {
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        index: "user_id"
        ^^^^^^^^^^^^^^^^
    }).coerceTo("ARRAY")), {
    ^^^^^^^^^^^^^^^^^^^^^^^^

    })
    ^^
}).changes()
^^

**Comment by neumino** [comment]
This is expected behavior.
[changes](http://www.rethinkdb.com/api/javascript/changes/) operates only on tables, and `getJoin` perform an inner queries and therefore returns a sequence, not a table.

It may be possible to have this work later if RethinkDB will support changefeeds on joined tables, but this is currently not available.
