### ISSUE TITLE
Better documentation around document lifecycle

### ISSUE THREAD

**Issue by marshall007** [neumino/thinky#170]
Thinky exposes several different event-related APIs including `Model.pre/post`, `Model.addListener`, and `Model.docAddListener`. It would be great if there were some documentation that walked us through the entire document lifecycle and explained exactly how and when each event gets triggered.

I also think there are cases where consolidating the API would be the best solution. For example, I can't think of a reason why we need past-tense events like `saved|deleted` on `Document` when you can just do `Model.post('save|delete')`.

**Comment by neumino** [comment]
Thanks for the suggestion @marshall007. I'll try to write the life cycle of objects. I just need to find some time :)

For the past tense for events like `saved`, it's because there is also the event `saving`.
`saving` was a way for people to have pre-hooks, but the limitation was that the hooks had to be synchronous. Now that hooks are available, it would make sense to remove them.

I don't really want to break stuff out of the blue, so for the next big release, I'll tag `saving` as deprecate, tell people to use hooks, and fire `save` (and `saved` for backward compability).
And eventually, I'll remove `saved` (after a few releases) except if some people have strong opinions and don't want to use hooks but events only.

**Comment by chrisfosterelli** [comment]
+1. Thinky has been awesome so far but sometimes the documentation is unclear to beginners with Rethink. Of course this is an easy thing for the community to help contribute to :)

**Comment by neumino** [comment]
So that's somehow documented here: http://thinky.io/documentation/api/model/#doceventemittersmethods

I guess it's kind of hard to find though. I tend to think that what's missing is "just" more examples (including full applications). I'll try to write a few when I'll have some time :)
