### ISSUE TITLE
The check to determine if the joined document is the correct type should be performed after _apply

### ISSUE THREAD

**Issue by phillips1012** [neumino/thinky#179]
If I want to do something like

```coffeescript
.getJoin
  comments:
    _apply: (x) -> x.count()
```

It shouldn't throw this

    Cannot coerce NUMBER to ARRAY

It'd be nice to see a fix to this, as I'd rather not load 300 objects into memory 10 times every single request.

**Comment by neumino** [comment]
Hello @phillips1012 

I just released 1.16.2 with a fix for that.
You have to pass an extra option `_array: false` if you do not want to coerce to an array.

Something like this in your case:
```
Posts.getJoin
    comments:
        _apply: (x) -> x.count()
        _array: false
```

The reason why thinky doesn't check the type itself is because you currently cannot bind a stream with `do`, and cannot do something like
`r.branch(seq.typeOf().eq("STREAM"), seq.coerceTo("ARRAY"), seq)` without having to compute twice `seq` (which can be expensive).

If streams are automatically coerce to arrays, this would remove the need for `_array` but this is not yet implemented - https://github.com/rethinkdb/rethinkdb/issues/2721

Thanks for the suggestion!
