### ISSUE TITLE
Model Inheritance?

### ISSUE THREAD

**Issue by nicholaswyoung** [neumino/thinky#193]
How would I configure Thinky to use an abstract model, and several inherited variants? Here's some basic psuedocode:

```javascript
class Account {
  // thinky Account model methods.
}

class User extends Account {
  // User only methods.
}
```

At this point, ```User.find()``` would look in the ```Accounts``` table, but only return records that were created by the ```User``` model. But ```Accounts.find()``` would look in the ```Accounts``` table, returning any Users (or other inherited models) that it finds, and tell me what type of models it found.

Maybe I missed it in the docs, but is there a clean way to handle this use case in RethinkDB/Thinky?

**Comment by neumino** [comment]
No, you cannot do that with thinky. Each model has its own table.

You can create a table `User` and define a method `getAccount` if you want.
```
User.ensureIndex('isAccount', r.row.hasFields('account'));
User.defineStatic('getAccount', function() {
    return this.getAll(true, 'isAccount');
})
```

Having two model sharing two tables is not something that is currently not on the roadmap as I don't see any good reasons for that. It make things slower (indexes are bigger)
and harder to manage (your data is not in "silos")

**Comment by neumino** [comment]
I'm closing this issue as I don't see any good reason to allow models to share the same table.
I'm happy to answer any questions, and I'm open to suggestions if you have a use case behind this.

**Comment by bobmoff** [comment]
I have the same need as nicholaswyoung. I am creating a game based of tiles. There is Land, Building & Unit .. and they all share properties that are bound to the Tile. Like: createdAt, updatedAt, coords, game, player. How would you recommend I create these models using Thinky ? (I am coming from Mongoose-land)

**Comment by esatterwhite** [comment]
I would have to agree, The first thing I wanted to do was create a base model with common fields and methods on it.

+1 for model inheritance.

Just the fact that the Model class is not actually the model you want makes it difficult to work with.

**Comment by sondun2001** [comment]
One way you can solve this is by creating a model that shares the same properties (e.g. TileUnit that has the common properties), then you can create a belongsTo / hasOne relationship between that your other models such as Land, Building, etc. Then when you fetch your building, using a getJoin, it will include the tileUnit properties.

**Comment by esatterwhite** [comment]
@neumino I don't think table level inheritance is what is needed. I think javascript level inheritance is what most people are after. I want to define a base model with common field, methods and sub class it so I don't have to write it many times over. 

I want each model to have its own table. But I also want models to be able to inherent fields, and methods.

**Comment by goors** [comment]
Hi, maybe someone can use this, since i had similar problem, lot of my models shared same fields.
So i did next. Make some file shared.js and define shared json properties as:

<pre>
import { thinky, type, r } from '../../default_logic/database'
module.exports.NameTranslations = {
  en: type.string(),
  de: type.string(),
  fr: type.string(),
  it: type.string()
}

module.exports.Media = {
  logo: type.string(),
  photos: type.array(),
  videos: type.array(),
  brochures: type.array(),
  text: type.string(),
  html: type.string(),
  short_text: type.string(),
}

//and so on
</pre>

and then in my  models i did this:
<pre>
import { NameTranslations, Media } from './shared'

export const SomeModel = thinky.createModel({
id: type.string().uuid(4),
//some other fields here
name_translations: NameTranslations,
media: Media
})
</pre>

And it is working.  I sort of took logic from Golang type sturct inheritance.
