### ISSUE TITLE
BUG: Defaults for array not supported? 

### ISSUE THREAD

**Issue by gebrits** [neumino/thinky#204]
I'm doing something like this: 

        tokens: type.array().default([]).schema(type.object().schema({
          accessToken: type.string(),
          kind: type.string()
        })),

My goal is to start every object with an empty array of tokens. 

I'm seeing the behavior that all instances share the same 'tokens' -object. E.g.: when a token T is added to instance A and afterwards instance B is created, the  token T becomes part of instance B. 

This cannot be intended behavior. Is this a bug, or is the way I'm defaulting to an empty array not supported?

**Comment by gebrits** [comment]
Doing the following instead seems to solve the issue.
  
        tokens: type.array().default(function() {
          return [];
        }).schema(type.object().schema({
          accessToken: type.string(),
          kind: type.string()
        })),

**Comment by neumino** [comment]
Hum, this is a bug. Looking into it now.

**Comment by neumino** [comment]
Oh never mind, I misread it. This is actually expected.

When you write `.default([])` thinky just use the value passed in `default` as the default value. An array in JavaScript is an Object and is passed by reference, so the value will be shared between instances (since the value here is a reference).

If you want a new array, you have to create a new array everytime, which is why the function works fine.

**Comment by marshall007** [comment]
@neumino I would still consider this a bug because thinky actually does handle the `Object` case, thus not handling the `Array` case is inconsistent. I think this would be fixed by avoiding the `util.isPlainObject` check on [`/lib/schema.js#L101`](https://github.com/neumino/thinky/blob/0979ddad4c9ccfb058e86b7226ca2db38fee5181/lib/schema.js#L101) so that `value` gets deeply cloned regardless of type.

**Comment by neumino** [comment]
Arg, I thought about that while walking the dog.
Yea, thinky should just do a deepcopy like it does in objects. Thanks @marshall007 :)

Fix coming

**Comment by neumino** [comment]
Fixed and released in 1.16.10

**Comment by marshall007** [comment]
Oh, I just noticed line 56 in `generateVirtual` does the same thing, so that probably needs to be fixed as well. Also note that `util.deepCopy` already handles all the type checking so you could omit that entire if/else clause on [`/lib/schema.js#L101-L105`](https://github.com/neumino/thinky/blob/4534259990e1d5983e3a24d7d3daa37919c0b994/lib/schema.js#L101-L105) and always call `util.deepCopy(value)` and likewise in `generateVirtual`.
