### ISSUE TITLE
Cannot connect?

### ISSUE THREAD

**Issue by jontesehlin** [neumino/thinky#218]
Getting the following console output since update to latest release:
http://pastebin.com/CWqDMTf2

**Comment by neumino** [comment]
A few questions:
- Can you try to update the dependency rethinkdbdash? (to 2.0.1)
- How do you run rethinkdb? Do you run it in a container/vm?
- How many servers in your rethinkdb cluster and how did you start them?

**Comment by jontesehlin** [comment]
Already uses Rethinkdbdash v.2.0.1. 
Running i an docker container, using following image https://registry.hub.docker.com/_/rethinkdb/.
Just one server.

Work flawless using thinky v.1.16.6

**Comment by neumino** [comment]
If you pass `discovery: false` to the options, the error should go away.

Can you tell me what's the output of `r.db('rethinkdb').table('server_status')` and what's your docker's and local ip?

**Comment by jontesehlin** [comment]
r.db('rethinkdb').table('server_status') output: http://pastebin.com/skALtE81

10.7.7.201 is the local adress so I'm sort of confused about the 172.17.0.4 adress as It's not one of mine ;)

**Comment by jontesehlin** [comment]
Just saw this in the rethinkdb log:
Listening on addresses: 127.0.0.1, 172.17.0.4, ::1, fe80::42:acff:fe11:4%8
So it turns out this is probably a fault on my page, I'll have to check out the docker configuration!

Thanks anyway! :)

**Comment by neumino** [comment]
Sorry, I mean the output of `r.db('rethinkdb').table('server_status').run()`

Here's roughly what happens:
- rethinkdbdash creates some connection using localhost (or whatever you pass in `host`/`port`).
- It then find a server with ip `172.17.0.4` and think that `172.17.0.4 === localhost`
- it switch to `172.17.0.4` instead of `localhost` as it's more accurate.

The problem is that `172.17.0.4` is not accessible from outside the container (I guess you don't run thinky inside the same container) but rethinkdbdash doesn't that.

I believe if you can start rethinkdb by passing `--bind <ip of the host>` it should work, but you would have to try.

**Comment by jontesehlin** [comment]
Didn't manage to solve it in the docker container so migrated back to Rethinkdbdash v.1.16.13 :/
