### ISSUE TITLE
hasAndBelongsToMany - saveAll throws duplicate primary key error

### ISSUE THREAD

**Issue by markgeraty** [neumino/thinky#245]
First, thanks for an awesome library... thinky has been really helpful to our team.

If I have two models with a reciprocal hasAndBelongsToMany relationship established

```javascript
Model = thinky.createModel(modelNames[0], {
  id: type.string()
});

OtherModel = thinky.createModel(modelNames[1], {
  id: type.string()
});

Model.hasAndBelongsToMany(OtherModel, "links", "id", "id");
OtherModel.hasAndBelongsToMany(Model, "links", "id", "id");
```

I get an error when I try to create a document this way

```javascript
var otherDoc1 = new OtherModel({
  id: "one",
  links: [{id: "one"}]
});

var otherDoc2 = new OtherModel({
  id: "two",
  links: [{id: "one"}]
});

otherDoc1.saveAll().then(function(savedOtherModel1) {
  otherDoc2.saveAll().then(function(savedOtherModel2) {
    Model.get("one").getJoin().run().then(function(gotModel1) {
      assert.equal(gotModel1.links.length, 2);
      done();
    }).error(done);
  }).error(done);
}).error(done);
```

The error is

```
Error: Duplicate primary key "id":
{
  "id": "one"
}
{
  "id": "one"
}
```

Interestingly enough, it works if I first create the object that the model is created from.

```javascript
var doc1 = {
  id: 'one'
};

var otherDoc1 = new OtherModel({
  id: "one",
  links: [doc1]
});

var otherDoc2 = new OtherModel({
  id: "two",
  links: [doc1]
});
```

Is this the desired behavior?  If so, can that be changed?  

I can create a pull request with the test cases I added to document.js for this if that would be helpful.

Thanks!

**Comment by neumino** [comment]
Yes this is expected. Thinky doesn't overwrite documents since most of the time it's a mistake, not something you want to do on purpose.

The problem is what do you expect this to do if there is already a document with `id` of `1`.
Should you overwrite it, update it or throw an error?

```
var doc = new Model({id: 1});
doc.save()
```

Currently thinky throws because safe is better than wrong.
- Replacing the document is kind of dangerous since you can delete fields
- Updating the document may create an unvalid document

It's kind of hard to solve. The pull request https://github.com/neumino/thinky/pull/142 adds options for `Document.prototype.save`, but it's kind of hard to do well. To properly support this feature, doc.save should behave like `Model.get(...).update(...)` where a post validation run.

It also needs to properly recurse for joined documents. It's a decent chunk of work I think.

**Comment by neumino** [comment]
Basically if you want thinky to consider two elements as the same, you have to actually use the same reference. It seems like a reasonable trade-off I think.

**Comment by markgeraty** [comment]
Thank you for the quick reply!  That definitely makes sense, I can see the difficulty.  Being able to specify the conflict resolution, like in the PR you mentioned, would be really helpful.

For now, I will just fetch the joined documents from the database if they already exist before using ```document.saveAll()```.

Thanks for your help!

**Comment by markgeraty** [comment]
So I have the above working for newly created documents ... before calling saveAll(), I replace all of the objects in the `links` field with references to one in the database if they exist.

However, I can't get this to actually work when updating the `OtherModel` record from above via a merge() with another document. 

This works:

```javascript
OtherModel.get('one').getJoin().then(function(gotOtherDoc1) {
  gotOtherDoc1.links.push({id: 'three'});

  replaceWithReferences(gotOtherDoc1, function(refOtherDoc1) {
    refOtherDoc1.saveAll().then(function(savedOtherDoc1) {
      Model.get('three').getJoin().run().then(function(gotDoc3) {
        assert.equal(gotDoc3.links.length, 1);
        assert.equal(gotDoc3.links[0].id, 'one');
        done();
      });
    });
  });
});
```

But, if I do a merge instead of the push, it does not work...

```javascript
var updatedLinks = {
  links: [
    {id: 'three'}
  ]
};

// now, update otherDoc1
OtherModel.get('one').getJoin().merge(updatedLinks).then(function(gotOtherDoc1) {
  replaceWithReferences(gotOtherDoc1, function(refOtherDoc1) {
    refOtherDoc1.saveAll().then(function(savedOtherDoc1) {
      Model.get('three').getJoin().run().then(function(gotDoc3) {
        // this fails
        assert.equal(gotDoc3.links.length, 1);
        assert.equal(gotDoc3.links[0].id, 'one');
        done();
      });
    });
  });
});
```

Is there a special workflow to merge the relations of a hasAndBelongsToMany relationship?

**Comment by neumino** [comment]
What's the code for `replaceWithReferences`?

**Comment by markgeraty** [comment]
Its pretty crude at the moment, but I think it properly replaces objects with references from the database when they exist?

```javascript
// replace elements in links with database reference where ids are equal
function replaceWithReferences(otherDoc, callback) {
  Model.run().then(function(allDocs) {
    for (var docCounter = 0; docCounter < allDocs.length; docCounter++) {
      for (var linksCounter = 0; linksCounter < otherDoc.links.length; linksCounter++) {
        if (allDocs[docCounter].id === otherDoc.links[linksCounter].id) {
          otherDoc.links[linksCounter] = allDocs[docCounter];
        }
      }
    }

    callback(otherDoc);
  })
}
```

**Comment by neumino** [comment]
So I initally misread that and flagged https://github.com/neumino/thinky/issues/281 as a duplicate. This is expected behavior at the moment (whether it's good or not is another question though).

You merge the updated link in the server, so thinky believe that they are already saved since they are retrieved from a query. Therefore, when you call `saveAll`, it will only save the document (not the relation since it was already saved).
