### ISSUE TITLE
Soft deleting

### ISSUE THREAD

**Issue by gjuchault** [neumino/thinky#258]
Hi,

That could be great if there was any possibility of making `delete()` soft : that means creating a field `deleted_at`, making it `null` by default, and setting a date on it when deleting it.
That means that every method should include 
```js
.filter(function (item) {
  return item.deleted_at !== null;
});
```

**Comment by neumino** [comment]
This is a TTL feature and should be done in RethinkDB, not thinky.

Feel free to chime in:
https://github.com/rethinkdb/rethinkdb/issues/4008

**Comment by gjuchault** [comment]
Well this is not supported in any database (sql nor nosql) because this is an extension on the actual way of doing things in database (using update to delete). And that is exactly what an orm should do.
http://laravel.com/docs/5.1/eloquent#soft-deleting
https://github.com/l3pp4rd/DoctrineExtensions/blob/master/doc/softdeleteable.md
https://github.com/CakeDC/utils/blob/ea48ed95b62517ddb046a46c17638726242121da/Model/Behavior/SoftDeleteBehavior.php
https://www.djangopackages.com/grids/g/deletion/

And well, there is no one DB that uses a column `deleted_at`. Please reconsider it

**Comment by neumino** [comment]
Reopening since it's not just TTL.

There are a few reasons why soft deleting is a bad idea for thinky:

1. The cost in terms of performance is huge and not acceptable. Adding a `filter` before each method is not doable because that requires a table scan. If we make the filter use an index, then all your indexes must be compound indexes, which make things harder to use

2.  It's something you can do if you need to
```
Model.define('softDelete', function() {
  this.deleteAt = new Date();
  return this.save();
})

Model.defineStatic('getActive', function() {
  return this.filter(function(doc) { return hasFields("deleteAtl") })
  // or the equivalent with an index
})
```

3. The appropriate way is to move these documents to another table I think. You still get a fast access to your valid data and can query your "deleted records" table when you need to.

**Comment by gjuchault** [comment]
> Adding a filter before each method is not doable because that requires a table scan

Fair enough. But the filter is before the final .run command (but it still is a big perf loss).

> Adding a filter before each method is not doable because that requires a table scan

Absolutly.

Well I guess in Rethink (and nosql generally; even if I saw some implementations in php) that is not the way to do :)
