### ISSUE TITLE
Whats about setInsert, append, prepend?

### ISSUE THREAD

**Issue by alexsalas** [neumino/thinky#312]
Example:
Model.get("index")('array').append("item")

**Comment by neumino** [comment]
These methods are already available, though they modify a copy of the document, not the document itself. I don't think thinky should add these methods or overwrite them because:
- Thinky follows RethinkDB API and just add a few commands related to joins 
- It's actually hard to add a method that would update inplace. It requires parsing the whole query and dealing with edge cases - it's basically implementing something close to what reqlite is doing.
