### ISSUE TITLE
Disable automatic table creation

### ISSUE THREAD

**Issue by chrisfosterelli** [neumino/thinky#332]
Is it possible to have Thinky disable automatic table creation?
I'd be OK with those tables throwing an error when I attempt to query them.

My motivation stems from https://github.com/rethinkdb/rethinkdb/issues/2975, which makes it clear that if I was to launch a set of processes all using Thinky then I may end up with table duplicates. I'd prefer to be able to disable this and manually create the tables myself.

**Comment by neumino** [comment]
To answer your question, you can pass `{init: false}` as the third argument of `thinky.creaeModel` to disable table/indexes creation.

To answer your concern, if a table already exists, thinky doesn't throw. The only case where you could have issues if you create at the same time the same table.

Since it came up recently in https://github.com/neumino/thinky/pull/329, the appropriate solution in prod is to do the following:

1. Pass `{init: false}` to all your node processes
2. Every time you want to create a new model/index you should run the following script
```
var thinky = require(__dirname+"thinky.js")
var model1 = require(__dirname+"/model1.js");
var model2 = require(__dirname+"/model2.js");
// ...
var modelN = require(__dirname+"/modelN.js");
Promise.all([model1.ready(), model2.ready(), ..., modelN.ready()]).then(function(result) {
  // console.log("Success")
  thinky.r.getPoolMaster().drain()
}).error(function(err) {
  // handle err
})
```

Where each `model.js` file is similar to what is described here
http://thinky.io/documentation/architecture/
That is to say you should define your tables + relations + indexes (`ensureIndex`)

Once the script exists without error, you can push your new models/indexes without any issue.
If you push them before the script finishes, some queries may fail (like if an index is not found).

**Comment by chrisfosterelli** [comment]
@neumino Dang! I took a look but completely missed `{ init : false }`. That's what I was looking for, sorry about the redundant question.

Thanks!
