### ISSUE TITLE
Changes feed misbehaving

### ISSUE THREAD

**Issue by andela-omesanni** [neumino/thinky#397]
Hi,
I have a notification model that I listening for changes. Anytime, i add something to the notification table, when the change feed triggers, I see three print outs of my console.log statements. I don't know why this is the case because I was expecting to see only one print out. I am worried because I need to send the notification to the front end and i do not want it sending duplicate data.

I was wondering if you have any answer to this problem. Thanks

```javascript
Notification.changes().then(function(feed) {
  feed.each(function(error, doc) {
    if(!error) {
      if(doc.getOldValue() == null) {
        console.log(doc.isSaved(), doc.getOldValue());
      }
    }
  });
}).error(function(error) {
  console.log(error);
});
```

**Comment by neumino** [comment]
Works fine for me, you probably just have some code that prints multiple time the change...

**Comment by andela-omesanni** [comment]
does your own just prints once? Also is it possible to chain getJoin() before the .changes() because i tried doing that and it wasn't fetching the joined documents

**Comment by neumino** [comment]
It get printed just once.
And no you cannot use `getJoin` before `changes`. RethinkDB doesn't support changefeed on joins yet (though it's planned).

**Comment by ablankenship10** [comment]
Is there a way to use getJoin AFTER changes? How would I go about populating the relations of my document that I just received from a change feed? Is there a function to use on the document itself to populated it, rather than as part of the query? Something like:

```
db.Chat.changes().then(function (feed) {
  feed.each(function (error, doc) {
    if (error) {
      console.warn(error);
    } else {
        doc.getJoins({field1: true, fieldN:true}).then(function(doc){
               //send populated document to socket
        });
    }
  });
})
```

This way you could have a document retrieved at anytime in the past and populate the joins as needed later.

**Comment by neumino** [comment]
I believe this should work:
```
db.Chat.changes().map(function(change) {
   r.branch(
    change('new_val').ne(null),
    change('new_val'),
    change('old_val')
  )
}).getJoin(...).execute()
```

I believe you can't use `run` now.

**Comment by danieldunderfelt** [comment]
I'm also seeing this. This is my changefeed:

```
PostModel
    .changes()
    .then(feed => {
      feed.each((err, doc) => {
        console.log(doc.id)
      })
    })
```

Sometimes it works and only logs an individual ID once, sometimes twice, sometimes more. It's a bit random, so I don't wonder if you can't replicate it @neumino. My `PostModel` has three `belongsTo` relationships for what it's worth.

The RethinkDB data explorer only reports one change, so the bug is in Thinky or Rethinkdbdash.
