### ISSUE TITLE
error refactoring

### ISSUE THREAD

**Issue by mbroadst** [neumino/thinky#417]
I took an initial stab at error refactoring here in #231 which sort of fell by the wayside, but there [has](https://github.com/neumino/thinky/issues/352) [been](https://github.com/neumino/thinky/issues/395) [sufficient](https://github.com/neumino/thinky/issues/395) [discussion](https://github.com/neumino/thinky/issues/328) to warrant a discussion of refactoring.

The first step I took (in #231) was to unify all Errors as subclasses of a base `ThinkyError`, the benefit being mainly one of error consistency, as well as being able to catch all thinky-specific errors (currently all thinky errors are just "inherit" Error and I can't provide a catchall).  This would also open the door for implementing custom `ThinkyError`s for use with e.g. mixins.

Secondly, a point was brought up about not using `"use strict"` in the file, which I believe was properly refuted by my comments there. I would love an explanation for why not to use strict mode, maybe I've been making a mistake my whole time using node.

I think these changes set the stage for the improvements outlined in #328, to make validation errors more programmatically accessible (my guess is that this is the primary use case for them). I'll let discussion on those continue over there, and maintain this issue simply as a discussion for refactoring existing errors.

Thanks!

**Comment by neumino** [comment]
Ok, let's make this issue only about error refactoring. I thought that RethinkDB would bring error code, but it has been pretty long and I haven't heard about that so let's start with Thinky.

On top of my head, here's what I can think of
- validation error
- document not found
- invalid write
- duplicate primary key
- programmer error (passing a negative length for an array for example).

1. The main pain from my understanding is around validation error right? Because they just give a string that you have to run against a regex. So let's have the following fields:
- `message`: The same as what we have now
- `path`: an array to the field that did throw. For example for
```
{
  foo: {
    bar: [ {buzz: 2}, {buzz: 3}]
  }
}
// The paths could be:
  - ['foo']
  - ['foo', 'bar']
  - ['foo', 'bar', 0]
  - ['foo', 'bar', 0, 'buzz']
  - ['foo', 'bar', 1, 'buzz']
```
- `type`: Not exactly sure what to put here, The error could be: 
  * field missing
  * field null
  * wrong type
  * custom validator failed

For document not found we could add the primary key that did not return in an extra field. So we would have `message` and `primaryKey`
Same for duplicate primary key

I think invalid write errors are fine the way they are.


2. Add error code, so each type has an error code. To avoid issues with later with RethinkDB errors, we could make all errors have an extra field `thinkyError: true` or have them be an instance of a function `ThinkyError`

3. #328 brings the issue of returning all validation errors and not just one. We could at that time add a new type `MultipleValidationError` where there's a field `errors` that is an array of `ValidationError`.

Did I forget something? Point 1. is the main issue right?

**Comment by neumino** [comment]
Ah we should also move to bluebird 3 and update the relevant errors to be operational.

**Comment by mbroadst** [comment]
I think the only thing missing an optional `original` (or something similarly named) to optionally include the originating rethinkdb (or rethinkdbdash in this case) error, in case the user wants access to that? (I've found this to be a sufficient pattern in other projects).

Making all of these errors operational should be trivial if they inherit the base ThinkyError, I'll put together a PR for discussion.

**Comment by mbroadst** [comment]
On the topic of operational errors, once you have a proper hierarchy of errors there is no longer a need to deem something an operational error as you can just catch the error explicitly switching from:
`.error(function() { ... })` to `.catch(errors.ThinkyError, function() { ... })` (in the event that you want to catch all thinky related errors), or by explicit reference to a single error: `.catch(errors.DocumentNotFound, function() { ... })`, I find this greatly improves readability personally and would allow an update to bluebird 3.x with limited modification
