### ISSUE TITLE
insert queries randomly return a model instance

### ISSUE THREAD

**Issue by contra** [neumino/thinky#425]
```js
User.insert(doc, {conflict: 'update', returnChanges: true}).run((err, res) => {
  console.log(res) // a model instance
})
```

Expected result: Normal rethinkdb result, as documented [here]()

Actual result: Normal rethinkdb result (SOMETIMES), other times it is an instance of a model (wtf?)

**Comment by neumino** [comment]
This returns a model (all the time) or return an error if validation fail (and it should most of the time, except if your schema actually match a rethinkdb write result.

You probably want `User.save` instead of `User.insert`. Thinky wraps all queries and `run` always return an instance of a model while `execute` return the raw response.

**Comment by contra** [comment]
Got it, execute has the desired behavior. Thanks!
