### ISSUE TITLE
Feature Request: model.saveAll (and honor attributes)

### ISSUE THREAD

**Issue by admc** [neumino/thinky#469]
It would be very helpful if I could do a bulk save of objects ( ie. User.save([user1, user2, user3])) but simultaneously save their associations (like a saveAll)?

This way if I create a bunch of users, all with profile associations, I can get the optimization out of creating them all at once, and not have to re-iterate and create their profile associations.

Great project, refactoring my app is going very well. Thanks!

**Comment by neumino** [comment]
This is probably not going to happen because of all the edge cases that this operation would create. Imagine the simple case where you do

If I make it sequential, then there's no more benefits than calling `saveAll` multiple times (except maybe a nicer syntax).
If I insert by bulks and things have conflicts, there are tons of edge cases. Like if a joined document is already save, it's going to fail. Then we'll probably end up with a weird inconsistent state.
What if the same joined document is provided by multiple users? Or if a user in the bulk insert is also in relation with another user?
