### ISSUE TITLE
hasMany getJoin -> pluck possible?

### ISSUE THREAD

**Issue by makkesk8** [neumino/thinky#545]
Is there a way to pluck keys of joined documents? The below example may not be the correct way doing it with thinky and it lacks the proper documentation. However, after looking at the documentation of rethinkdb this should be sufficient?

Example:
```
User.get('IDHERE').getJoin({ account: true}).pluck({ account: { 'createdAT': true }})
```

the above example does not work and spits out:

```
Unhandled rejection ReqlDriverError: `toJSON` takes 0 argument, 1 provided after:
r.uuid()
```

**Comment by neumino** [comment]
pluck after `getJoin` works fine, your query works.

The error your are showing is probably because you are trying to serialize a ReQL term. Maybe you have a field with a `.default(r.row())` on your account model?

**Comment by makkesk8** [comment]
@neumino Yea I actually have a ```.default(r.row())``` but why does that matter?

**Comment by neumino** [comment]
When you retrieve your document, because you pluck the field and do not get back this field, thinky sets is to `r.now()`.

Then you probably call something like JSON.stringify on this object or try to send it over the wire (which call JSON.stringify under the hood. You are trying to serialize `r.now`, which throws an error (because of the `toJSON` implementation.

**Comment by makkesk8** [comment]
@neumino In other words, you can only use ```.default(r.now())``` if you don't need to pluck the field?

And for the record I don't use ```JSON.stringify``` since it does it under the hood. And I'm using the ```.default(r.now())``` for the created_at and updated_at fields in my model.

Is there a way to pluck and keep the default values? or is there a better way to do this?

**Comment by neumino** [comment]
Not sure there's a better way to do this. The philosophy on which thinky was built was that document should be fully returned.

You can use `execute` if you don't want to create an instance of the model and validate the data. You can also use `.default(function() { return new Date() })` which is more or less the same as using `r.now()` and should prevent the error you are seeing.

**Comment by lilhamad** [comment]
using something like r.now and are r.uuid() throws error when dealing with Json atimes use the following instead

function() { return new Date() } instead of r.now
new Guid().StringGuid instead of r.uuid()
Like below:
import { Guid } from 'js-guid';
var Order = thinky.createModel("Order", {
    id: type.string().default(new Guid().StringGuid),
    updatedAt: type.date().default(function() { return new Date() })
}); 
install js-guid with npm install js-guid
