### ISSUE TITLE
Ignored fields on pluck operation are included in response with default value

### ISSUE THREAD

**Issue by alantrrs** [neumino/thinky#567]
Consider the following model:
```js
// Model
var User = thinky.createMode('User', {
  username: String,
  otherField: String,
  state: type.string().default('default value')
})
```
Then when using it you'll find that the fields that are supposed to be ignored are instead present with the default value. Which would be incorrect if the value has a different value in database. These fields should not be included in the response.
```js
// Query
User.pluck('username', 'otherField').run().then(function (users) {
   console.log(users) // users[0].state === 'default value' which is wrong
})
```

**Comment by neumino** [comment]
Hum, that's not possible at the moment because thinky doesn't know that you plucked value. Thinky doesn't play well with partial document because it was built on the assumption that if an instance of a document is returned, the document should be complete.

If it's not, then you don't need the model, in which case you can just use `execute` instead of `run`
